/*!
 * ImideoScript vab76676 (2014-01-27) | www.imideo.com
 */
var imideo=function(p,I){var ra,sa,ta,ua,fa,va,wa;function xa(a){"undefined"!==typeof console&&console.log(a);A&&u&&A.call(function(){imideo.ui_log(a)})}var ga=!1,r=ga?function(a){xa(a)}:function(){},m=p.document,T=m.location,U=p.encodeURIComponent,G=p.setTimeout,K=p.clearTimeout,V=p.parseInt,W=p.isNaN,q=!1,u=!1,n={ALL:{visible:!1,design:"normal"},MBC:{visible:!1,design:"normal"}},v="";if(!function(){var a=m.getElementsByTagName("head")[0],f=a.getElementsByTagName("script"),k=m.getElementsByTagName("body")[0],
l=f.length-1,j=!0;try{if(j=k.getAttribute("contentEditable"),"true"!==j)return!1}catch(h){return!1}do k=f[l],(k.src&&-1<k.src.indexOf("static.image2play.com")||-1<k.text.indexOf("static.image2play.com"))&&a.removeChild(k);while(l--);return!0}()){var B;B=m.getElementsByTagName("script");var t=B.length,X={},ya=0;"undefined"!==typeof p.imideo_appkey&&"f8da5Hf0d7jad09m4abdb09c1V7702kcc0cx28a4"===p.imideo_appkey&&(n.KBS={visible:!1,design:"normal"});for(var ha=0;ha<t;ha++){var s=B[ha].id;0===s.indexOf("i2p-")&&
(X[s]=m.getElementById(s).src,ya++,"i2p-extension-sbs"===s?(n.SBS={visible:!0,design:"normal"},q=!0,v=m.getElementById(s).src):"i2p-extension"===s?(0<X[s].indexOf("imideo.publisher.js")?(n.ALL={visible:!0,design:"normal"},q=!0):0<X[s].indexOf("imideo.samsung.js")?(n.KBS={visible:!0,design:"samsung"},n.KBS1={visible:!0,design:"samsung"},n.KBS2={visible:!0,design:"samsung"},n.SBS={visible:!0,design:"samsung"},n.MBN={visible:!0,design:"samsung"},n.TV_CHOSUN={visible:!0,design:"samsung"},n.CHANNEL_A=
{visible:!0,design:"samsung"},n.JTBC={visible:!0,design:"samsung"},q=!1,u=!0):(n.ALL={visible:!0,design:"normal"},q=!1),v=m.getElementById(s).src):"i2p-extension-nate"===s?(n.KBS={visible:!0,design:"normal"},n.KBS1={visible:!0,design:"normal"},n.KBS2={visible:!0,design:"normal"},n.SBS={visible:!0,design:"normal"},n.MBN={visible:!0,design:"normal"},n.TV_CHOSUN={visible:!0,design:"normal"},n.CHANNEL_A={visible:!0,design:"normal"},n.JTBC={visible:!0,design:"normal"},q=!0,v=m.getElementById(s).src):"i2p-extension-zum"===
s?(n.KBS={visible:!0,design:"altoolbar"},n.KBS1={visible:!0,design:"altoolbar"},n.KBS2={visible:!0,design:"altoolbar"},n.SBS={visible:!0,design:"altoolbar"},n.MBN={visible:!0,design:"altoolbar"},n.TV_CHOSUN={visible:!0,design:"altoolbar"},n.CHANNEL_A={visible:!0,design:"altoolbar"},n.JTBC={visible:!0,design:"altoolbar"},n.CJ_ENM={visible:!0,design:"altoolbar"},q=!0,v=m.getElementById(s).src):"i2p-extension-est"===s&&!1===n.ALL.visible&&(n.ALL={visible:!0,design:"altoolbar"},q=!1,v=m.getElementById(s).src),
0<X[s].indexOf("debug=true")&&(r=(ga=!0,function(a){xa(a)})))}B=ya;t=(t=m.getElementById("imideo-setting"))?t.getAttribute("content").toLowerCase():"yes";if("undefined"!==typeof imideo||"no"===t){try{if("undefined"===typeof imideo.SCRIPT_IDS_LENGTH||B===imideo.SCRIPT_IDS_LENGTH)return r("PASS"),imideo}catch(Ra){return r("PASS"),imideo}try{imideo.set_script_config(n),imideo.set_publisher_script(q),imideo.script_parameter(v),imideo.ui_refresh()}catch(Sa){}return imideo}var x="",L="",M=!1,D=!1,C=T.href,
N=T.protocol+"//",ia=!1,za=!1,Y="timeout",ja="not_matched";ra=0;sa=1;ta=2;ua=3;fa=4;va=5;wa=6;var H=-1,Z="",ka=200,la=null,t=function(){this.callbacks=[]};t.prototype={add:function(a){this.callbacks.push(a)},run:function(){for(var a=this.callbacks.length,f=0;f<a;f++)this.callbacks[f]();this.callbacks=[]}};var Aa=function(a){function f(a,b,c,e,f,d){a=h(h(b,a),h(e,d));return h(a<<f|a>>>32-f,c)}function k(a,b,c,e,d,g,k){return f(b&c|~b&e,a,b,d,g,k)}function l(a,b,c,e,d,g,k){return f(b&e|c&~e,a,b,d,g,
k)}function j(a,b,c,e,d,g,k){return f(c^(b|~e),a,b,d,g,k)}function h(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}for(var e=Array(a.length>>2),b=0;b<e.length;b++)e[b]=0;for(b=0;b<8*a.length;b+=8)e[b>>5]|=(a.charCodeAt(b/8)&255)<<b%32;a=8*a.length;e[a>>5]|=128<<a%32;e[(a+64>>>9<<4)+14]=a;a=1732584193;for(var b=-271733879,c=-1732584194,d=271733878,g=0;g<e.length;g+=16){var n=a,m=b,p=c,r=d;a=k(a,b,c,d,e[g+0],7,-680876936);d=k(d,a,b,c,e[g+1],12,-389564586);c=k(c,d,a,b,e[g+
2],17,606105819);b=k(b,c,d,a,e[g+3],22,-1044525330);a=k(a,b,c,d,e[g+4],7,-176418897);d=k(d,a,b,c,e[g+5],12,1200080426);c=k(c,d,a,b,e[g+6],17,-1473231341);b=k(b,c,d,a,e[g+7],22,-45705983);a=k(a,b,c,d,e[g+8],7,1770035416);d=k(d,a,b,c,e[g+9],12,-1958414417);c=k(c,d,a,b,e[g+10],17,-42063);b=k(b,c,d,a,e[g+11],22,-1990404162);a=k(a,b,c,d,e[g+12],7,1804603682);d=k(d,a,b,c,e[g+13],12,-40341101);c=k(c,d,a,b,e[g+14],17,-1502002290);b=k(b,c,d,a,e[g+15],22,1236535329);a=l(a,b,c,d,e[g+1],5,-165796510);d=l(d,a,
b,c,e[g+6],9,-1069501632);c=l(c,d,a,b,e[g+11],14,643717713);b=l(b,c,d,a,e[g+0],20,-373897302);a=l(a,b,c,d,e[g+5],5,-701558691);d=l(d,a,b,c,e[g+10],9,38016083);c=l(c,d,a,b,e[g+15],14,-660478335);b=l(b,c,d,a,e[g+4],20,-405537848);a=l(a,b,c,d,e[g+9],5,568446438);d=l(d,a,b,c,e[g+14],9,-1019803690);c=l(c,d,a,b,e[g+3],14,-187363961);b=l(b,c,d,a,e[g+8],20,1163531501);a=l(a,b,c,d,e[g+13],5,-1444681467);d=l(d,a,b,c,e[g+2],9,-51403784);c=l(c,d,a,b,e[g+7],14,1735328473);b=l(b,c,d,a,e[g+12],20,-1926607734);a=
f(b^c^d,a,b,e[g+5],4,-378558);d=f(a^b^c,d,a,e[g+8],11,-2022574463);c=f(d^a^b,c,d,e[g+11],16,1839030562);b=f(c^d^a,b,c,e[g+14],23,-35309556);a=f(b^c^d,a,b,e[g+1],4,-1530992060);d=f(a^b^c,d,a,e[g+4],11,1272893353);c=f(d^a^b,c,d,e[g+7],16,-155497632);b=f(c^d^a,b,c,e[g+10],23,-1094730640);a=f(b^c^d,a,b,e[g+13],4,681279174);d=f(a^b^c,d,a,e[g+0],11,-358537222);c=f(d^a^b,c,d,e[g+3],16,-722521979);b=f(c^d^a,b,c,e[g+6],23,76029189);a=f(b^c^d,a,b,e[g+9],4,-640364487);d=f(a^b^c,d,a,e[g+12],11,-421815835);c=
f(d^a^b,c,d,e[g+15],16,530742520);b=f(c^d^a,b,c,e[g+2],23,-995338651);a=j(a,b,c,d,e[g+0],6,-198630844);d=j(d,a,b,c,e[g+7],10,1126891415);c=j(c,d,a,b,e[g+14],15,-1416354905);b=j(b,c,d,a,e[g+5],21,-57434055);a=j(a,b,c,d,e[g+12],6,1700485571);d=j(d,a,b,c,e[g+3],10,-1894986606);c=j(c,d,a,b,e[g+10],15,-1051523);b=j(b,c,d,a,e[g+1],21,-2054922799);a=j(a,b,c,d,e[g+8],6,1873313359);d=j(d,a,b,c,e[g+15],10,-30611744);c=j(c,d,a,b,e[g+6],15,-1560198380);b=j(b,c,d,a,e[g+13],21,1309151649);a=j(a,b,c,d,e[g+4],6,
-145523070);d=j(d,a,b,c,e[g+11],10,-1120210379);c=j(c,d,a,b,e[g+2],15,718787259);b=j(b,c,d,a,e[g+9],21,-343485551);a=h(a,n);b=h(b,m);c=h(c,p);d=h(d,r)}e=[a,b,c,d];a="";for(b=0;b<32*e.length;b+=8)a+=String.fromCharCode(e[b>>5]>>>b%32&255);e=a;a="";for(c=0;c<e.length;c++)b=e.charCodeAt(c),a+="0123456789abcdef".charAt(b>>>4&15)+"0123456789abcdef".charAt(b&15);return a},O,Ba=function(){return/loaded|interactive|complete/.test(m.readyState)},w=function(){!D&&m.addEventListener?p.removeEventListener("load",
w,!1):p.detachEvent("onload",w);ma.run();$=!0},aa=function(){!D&&m.addEventListener?(r("DOMContentLoaded"),m.removeEventListener("DOMContentLoaded",aa,!1),w()):Ba()&&(r("DOMContentLoaded"),m.detachEvent("onreadystatechange",aa),w())},Ca=function(a){var f={};if(-1<a.indexOf("?")){a=a.split("?").pop().split("&");for(var k=0;k<a.length;k++){var l=a[k].split("=");f[l[0]]=l[1]}}a=f.appkey;!q&&!u&&!a?a="H604cJ529fb7ef7k420049ffff6619M1b4f4c5fd":u&&!a&&(a="Bc6c0d03d6P524ft75a43ad8fs0721t8ac7Nc45e");x=a;
a=f.extkey;!q&&!u&&!a?a="undefined"!==typeof imideo_identifier?imideo_identifier:"":u&&!a&&(a="3e4c704b-f182-43e4-bd43-1448a859ba6d");L=a;(Z=(a=f.params)?decodeURIComponent(a):"")&&(Z="&"+Z);a=V(f.grade,10);W(a)&&(a=200);ka=a;la=f;r("APPKEY "+x+", EXTKEY "+L+", GRADE "+ka)},na=function(){return"Microsoft Internet Explorer"===navigator.appName},$=!1,ma=new t,D=na();ma.add(function(){function a(a){try{var b=p[a];delete p[a];var e=p[a];p[a]=b;return e}catch(f){return function(){try{return p.constructor.prototype[a].apply(p,
arguments)}catch(b){return p[a]}}}}function f(){var a=-1;na()&&/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return a}function k(){if(-1!==C.indexOf("cafe.naver.com/ArticleRead.nhn"))return delete Object.prototype.toJSON,!0;try{var a=!(na()&&9>f()),b;for(b in Object.prototype){if(!a)return!1;Object.defineProperty(Object.prototype,b,{value:Object.prototype[b],enumerable:!1})}}catch(e){}return!0}Ca(v);var l;l="now.olleh.com www.olleh.com coupang.com comic.naver.com 11st.co.kr ticketmonster.co.kr gmarket.co.kr esmplus.com shopping.naver.com www.naver.com auction.co.kr map.daum.net cu-media.co.kr hyplove.co.kr unimedihospital.co.kr sktsdinfo.com m.naver.com m.blog.naver.com m.cafe.daum.net m.cafe.naver.com postman.co.kr youku.com 77wh.blogspot.kr page.uplus.co.kr m.wedisk.co.kr hyundaihmall.com encar.com halfclub.com gsshop.com m.bobaedream.co.kr m.nate.com m.webtoon.daum.net www.gomdisk.net mobile.sportsseoul.com m.comics.nate.com m.cartoon.media.daum.net m.imgur.com m.okoutdoor.com m.sports.media.daum.net 19insidenet.com www.lotte.com www.stylenanda.com m.shop.naver.com www.lgfashionshop.com www.stylenanda.com www.oclock.co.kr shop.beautynet.co.kr www.soo-a.co.kr wowtv.co.kr inisland.co.kr coway.co.kr".split(" ");
var j=l.length,h=!0;do if(-1!==C.indexOf(l[j-1])){h=!1;break}while(j--);if(l=h)if(l=k()){l=!1;do if(x&&L){if(q){h={"06fd0a766f7699d6dc0664c98dcaafae":{com:{imideo:1,imideomall:1},221:1},"07ee71747102ebefc699b4123beca584":1,"43359199b9f59146c1d3bbafa97c4822":{com:{soompi:1}},"227916606a78262439248e8b6538d169":{kr:{co:{sbs:1,mk:1,mt:1,edaily:1}},com:{dcinside:1,pullbbang:1,fnnews:1}},a8b7ec27a12e5709ccae1961341b72b1:1,"15d28f94d6be89579adcd6fb4d7ad73b":1,"2f238e88c451498d381b2133ea1eb6b2":1,"17d3ae82b7a3352c68a0a91f9bc910a3":1,
"0e0489c01079790c70cb82d8bfc42cba":1,"9d49316d73a7340ee4d929f2c8108b10":1,ebd264723c9bd1b6b966da1997038d14:1};h=h[Aa(x)];if(j=h!==I)a:{for(var j=T.hostname,j=j.split(".").reverse(),e=j.length,b=0;b<e&&"number"!==typeof h;b++)if(h=h[j[b]],h===I){j=!1;break a}j=1===h||0===h&&b===e}if(!j)break}l=!0}while(0)}M=l;-1!==C.indexOf("facebook.com")&&(l=f(),-1!==l&&8>l?M=!1:(a("setInterval"),G=a("setTimeout")));q&&(ia=/^https?:\/\/((((www(\.dev)?)|m)\.)?imideo\.com|121\.78\.228\.221)/i.test(C),za=/^http:\/\/isplus\.joins\.com\/?/i.test(C)&&
"/"===T.pathname);r("PAGE_URL "+C+", IS_ENABLED "+M+", MSIE "+D)});r("ready_promise : "+m.readyState);if(Ba())r("is_document_ready_state start ready()"),G(w,1);else if(!D&&m.addEventListener)r("wait for DOMContentLoaded"),m.addEventListener("DOMContentLoaded",aa,!1),p.addEventListener("load",w,!1);else{r("wait for DOMContentLoaded");m.attachEvent("onreadystatechange",aa);p.attachEvent("onload",w);var ba=!1;try{ba=null==p.frameElement&&m.documentElement}catch(Ta){}ba&&ba.doScroll&&function f(){if(!$){try{ba.doScroll("left")}catch(k){return G(f,
50)}w()}}()}O={script_parameter:Ca,is_ready:$,ready:function(f){$?f():ma.add(f)}};var E,Ea=function(f){if(0<=m.location.hostname.indexOf("daum")&&_regexp_nomatch.test(f.src))return!1;if(ia||za)return Da.test(f.src);var k=f.width;f=f.height;var l=k/f;return k>=P&&f>=Q&&20>l&&0.03<l},Ma=function(f,k){R.query_i2p(f,function(l){A.call(function(){k.clips=l;imideo.ui_add(f,k)})},function(){k.filtered=!0;k.objs=[]},!1)},Ga=function(){var f=m.images,k=f.length,l,j,h;for(l in y)y[l].objs=[];for(l=0;l<k;l++){j=
f[l];h=j.src;var e=Fa.exec(h);h=e?e[1]:h;Ea(j)&&(h in y?(e=y[h],!0!==e.filtered&&e.objs.push(j)):(r("selected: "+h),e={objs:[j]},y[h]=e,Ma(h,e)))}},Ha=function(){Ga();z&&(K(z),J=u?Math.min(J+Na,Oa):Math.min(J+Pa,Qa),z=G(Ha,J))},ca=!1,Ia=!1,Qa=6E3,Pa=500,Oa=1E3,Na=100,J,z,y,P,Q,Fa,Da;E={start:function(){if(!ca){if(!Ia){Ia=!0;P=V(la.minwidth,10);if(W(P)||50>P)P=q?150:u?200:290;Q=V(la.minheight,10);if(W(Q)||50>Q)Q=q?75:150;Fa=/^(http:\/\/thumb\.(mt\.co\.kr|mtstarnews\.com)\/[^\?]*)\?time=\d*$/i;Da=/^https?:\/\/[^#]*#forcedmatch/i;
_regexp_nomatch=/^https?:\/\/[^#]*#no_imideo/i}ca=!0;J=u?500:1E3;y={};Ga();z=G(Ha,J)}},stop:function(){ca&&(ca=!1,z&&(K(z),z=null))},is_valid_image:Ea};var R,oa=function(f,k,l){var j=new Image;l.push("appkey="+x);l.push("extension_key="+L);l.push("page_url="+U(m.location.href));l.push("image_url="+U(k));j.src=N+("i2p.enswer.net/v1/stat/"+f+"/")+"?"+l.join("&")},Ja=function(f,k,l){function j(){try{delete p[h]}catch(b){p[h]=I}}var h=("imideo_jsonp"+(l||Math.random())).replace(".",""),e=m.head||m.getElementsByTagName("head")[0]||
m.documentElement,b;p[h]=function(b){k(b);j()};b=m.createElement("script");b.src=f+"&callback="+h;b.async="async";b.onload=b.onreadystatechange=function(c,f){if(f||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,e&&b.parentNode&&e.removeChild(b),e=b=I};e.insertBefore(b,e.firstChild);return{abort:function(){if(b)b.onload(0,1);j();p[h]=function(){}}}},Ka=1E4,F={};R={query_i2p:function(f,k,l,j){function h(){q&&(q.abort(),q=null);n&&(K(n),n=null)}function e(){delete F[f];
h();g&&(K(g),g=null);s&&(s.abort(),s=null)}function b(b){var e=j?"manual_recognize_done":"auto_recognize_done";b=["width=0&height=0","duration="+((new Date).getTime()-p),"status_code="+u,"clip_ids="+b];oa(e,f,b)}function c(c){e();var d="";c===Y&&0<m?(d="NO_RESPONSE",r("no_response: "+f)):c===Y&&(d="TIMEOUT",r("timeout: "+f));H>=fa&&(d="OVMS_TIMEOUT",r("ovms_timeout: "+f));0.1>Math.random()&&b(d);l(c)}function d(){h();var p=["appkey="+x,"src="+U(f),"type=url"];j&&p.push("mode=manual");H=ra;var t="i2p.enswer.net/v2/image/",
w=null;if("P7cc1x1ce3L8b0aF6d0d008b4o042eKd74cU39eb"===x||"d7a7eq2226he8b8Jed90Yedf1f5887h52e4Ce95e"===x)t="api.imideo.com/v2/image/",w=Aa(U(f)),"https://"===N&&(t="i2p.enswer.net/v2/image/");q=Ja(N+t+"?"+p.join("&")+Z,function(h){q=null;u=h.status_code;var j;if(j=h.match){var p={},t=[],w=j.length,x,A,v,z,B;for(z=0;z<w;z++){var D=[];A=j[z];x=A.length;for(B=0;B<x;B++)v=A[B],"rtmp"===v.clip_type&&!(v.clip_id in p)&&(p[v.clip_id]=!0,D.push(v.clip_id));0<D.length&&t.push(D)}j=t}else j=[];if(0<j.length){H=
sa;j.iid=h.image_id||"";var C=j;j=C.length;h="[";for(p=0;p<j;p++)0<p&&(h+=","),h+='["'+C[p].join('","')+'"]';h+="]";r("matched: "+f);e();H=fa;g=G(function(){c(Y)},Ka);var E=f,y;y=Ja(N+"ovms.enswer.net/v3/enable_streaming?"+["clip_ids="+h,"thumbnail=1"].join("&"),function(c){delete F[E];y=null;var d=c.results;c=[];for(var g,h=null,j={},n=0;n<d.length;n++)if(g=d[n],!(g.error!==I&&620!==g.error.code||g.content_id in j&&!0!==g["default"])){j[g.content_id]=!0;var m=g,p=g.title,q=g.ep;p?!W(parseFloat(q))&&
isFinite(q)&&(p=p+" "+q+"\ud68c"):p="\uc81c\ubaa9\uc5c6\uc74c";m.title_display=p;g.content_distributor_display={CHANNEL_A:"CHANNEL A",MNET:"Mnet",ON_STYLE:"On Style",SBS_ESPN:"SBS ESPN",TVN:"tvN",TV_CHOSUN:"TV\uc870\uc120"}[g.content_distributor]||g.content_distributor;g.airdate=g.airdate||"";if(!0===g["default"]){h=!1;for(m=0;m<c.length;m++)if(c[m].content_id===g.content_id){c[m]=g;h=!0;break}h||c.push(g);h=g}else c.push(g)}null===h&&0<c.length&&(h=c[0]);c.default_item=h;if(0<c.length){H=va;r("ovms_received: "+
f);e();c.iid=C.iid;d="";g=c.length;for(j=0;j<g;j++)0<d.length&&(d+=","),d+=c[j].clip_id;b(d+",OVMS");c.default_item&&!0!==c.default_item.adult_content&&k(c)}else c=ja,e(),H=wa,c===ja?(d="OVMS_EMPTY",r("ovms_empty: "+f)):(d="OVMS_ERROR",r("ovms_error: "+f)),b(C[0][0]+","+d),l(c)});s=F[E]={abort:function(){y&&y.abort();delete F[E];y=null}}}else 300>V(h.status_code)?(r("rematch("+m+"): "+f),H=ta,m++,n&&K(n),n=G(d,3>m?3E3:1E3)):(r("not matched: "+f),H=ua,c(ja))},w)}var g=null,n=null,m=0,p=(new Date).getTime(),
q=null,s=null,u="",g=G(function(){c(Y)},Ka);j&&oa("manual_recognize",f,["width=0","height=0"]);d();return F[f]={abort:function(){e()}}},stop:function(){for(var f in F)F[f].abort(),delete F[f];F={}},send_stats:oa};var A,pa=new t,da=0;A={call:function(f){switch(da){case 0:pa.add(f);f=m.getElementById("i2p-extension-ui");var k;a:{k=m.getElementsByTagName("style");for(var l=k.length,j=0;j<l;j++)if(0===(D?k[j].styleSheet.cssText:k[j].innerHTML).indexOf(".imideo-c")){k=k[j];break a}k=I}f&&(f.parentNode.removeChild(f),
k&&k.parentNode.removeChild(k));da=1;f=u?"imideo.mobile.ui.js":"imideo.ui.js";var h=m.createElement("script");h.type="text/javascript";h.id="i2p-extension-ui";h.async="async";h.src=N+"static.image2play.com/"+f+"?_=1.1.2";"utf-8"!=m.charset&&(h.charset="utf-8");h.onload=h.onreadystatechange=function(){if(2!==da&&(!h.readyState||/loaded|complete/.test(h.readyState)))da=2,h.onload=h.onreadystatechange=null,h=I,ga&&u&&imideo.ui_log_start(),pa.run()};m.getElementsByTagName("head")[0].appendChild(h);break;
case 1:pa.add(f);break;case 2:f()}}};var qa,La=function(){ea&&(ea.abort(),ea=null)},ea=null;qa={match:function(f){La();A.call(function(){imideo.ui_match_start()});ea=R.query_i2p(f,function(k){A.call(function(){imideo.ui_match_end(f,k.iid,k.default_item)})},function(){A.call(function(){imideo.ui_match_end()})},!0)},stop:La};var t=function(){O.ready(function(){!S&&M&&(r("started"),E.start(),S=!0)})},S=!1;(q||u)&&t();return{start:t,stop:function(){O.ready(function(){if(S){r("stopped");E.stop();R.stop();
qa.stop();S=!1;try{imideo.ui_stop()}catch(f){}}})},match:function(f){O.ready(function(){M&&(r("match "+f),qa.match(f))})},refresh:function(){if(S){E.stop();E.start();try{imideo.ui_refresh()}catch(f){}}},is_valid_image:E.is_valid_image,APPKEY:function(){return x},EXTKEY:function(){return L},GRADE:function(){return ka},PUBLISHER_SCRIPT:q,set_publisher_script:function(f){q=f},set_script_config:function(f){n=f},get_script_config:function(){return n},IS_IMIDEO_COM:function(){return ia},send_stats:R.send_stats,
script_parameter:O.script_parameter,VERSION:"1.0.6",SCRIPT_IDS_LENGTH:B}}}(window);
